spring.application.name=springsecex

spring.security.user.name=user
spring.security.user.password=haswo

spring.datasource.url=jdbc:postgresql://localhost:5432/springsecex
spring.datasource.username=postgres
spring.datasource.password=haswo

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
